Iter5
sur1k1/go-metrics pull request #5
Opened 2024-10-05 13:05 UTC by sur1k1

2024-10-07 13:35 UTC, arttet requested changes
- [ ] Split the application into layers
https://github.com/golang-standards/project-layout
https://medium.com/@deanrubin/the-three-layered-architecture-fe30cb0e4a6#:~:text=The%20presentation%20layer%20is%20the,Update%20or%20Delete)%20operation%20flow.
- [ ] Please integrate CodeCov https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/
- [ ] Please read and use the Conventional Commits specification https://www.conventionalcommits.org/en/v1.0.0/
- [ ] Please integrate the linter https://github.com/golangci/golangci-lint-action
- [ ] Please delete deprecated constraints in CI
https://github.com/sur1k1/go-metrics/blob/c3169a397a44c51f85121c37fe008388539e1770/.github/workflows/mertricstest.yml#L67

2024-10-07 13:35 UTC, arttet commented on internal/agent/config/flags.go
> +	var opts AgentOptions
[SUGGESTION] If I were you, I would use `Builder` pattern.

2024-10-07 13:35 UTC, arttet commented on internal/agent/config/flags.go
> +	Address 				string `env:"ADDRESS"`
[CHANGE REQUEST] Please format your code.

2024-10-07 13:35 UTC, arttet commented on internal/agent/metric/metric.go
> +	MetricUpdaterIntf
[CLARIFICATION] What is it?

2024-10-07 13:35 UTC, arttet commented on internal/agent/metric/metric.go
> +	for {
[CHANGE REQUEST] Please don't use infinite loops

2024-10-07 13:35 UTC, arttet commented on internal/server/handlers/metric_list.go
> +func MetricListHandler(s AllMetricsGetter) http.HandlerFunc {
[CHANGE REQUEST] It should be a method.

2024-10-07 13:35 UTC, arttet commented on internal/server/handlers/update_handler.go
> +	Gauge = string("gauge")
```suggestion
	Gauge = "gauge"
```

2024-10-07 13:35 UTC, arttet commented on internal/server/handlers/update_handler.go
> +	Gauge = string("gauge")
```suggestion
	GaugeTypeStr = string("gauge")
```

2024-10-07 13:35 UTC, arttet commented on internal/server/handlers/update_handler.go
> +	Gauge = string("gauge")
[CHANGE REQUEST] Please don't repeat yourself.

2024-10-08 03:52 UTC, sur1k1 commented on internal/agent/metric/metric.go
> +	for {
What to use instead?

2024-10-14 11:30 UTC, arttet requested changes

2024-10-14 11:30 UTC, arttet commented on .github/workflows/mertricstest.yml
>          if: |
[CHANGE REQUEST] This test won't run in `main`. But we have to run it there.

2024-10-14 11:30 UTC, arttet commented on cmd/agent/main.go
> +		panic(err)
[CHANGE REQUEST] Please don't panic.
https://github.com/uber-go/guide/blob/master/style.md#dont-panic

2024-10-14 11:30 UTC, arttet commented on cmd/agent/main.go
> +		os.Exit(0)
[SUGGESTION] This is not a graceful shutdown.

2024-10-14 11:30 UTC, arttet commented on internal/agent/metric/metric.go
> +	reportForm			string = "http://%s/update/%s/%s/%v"
[SUGGESTION] Please format your code

2024-10-14 11:30 UTC, arttet commented on internal/agent/metric/metric.go
> +	for {
[SUGGESTION] Please don't use infinite loops.

2024-10-14 11:30 UTC, arttet commented on internal/agent/metric/metric.go
> +	for name, value := range m.CounterMap{
[SUGGESTION] This function has a huge Cognitive Complexity.

2024-10-14 11:30 UTC, arttet commented on internal/server/rest/update_handler.go
> +func (s *UpdateHandler) Update() http.HandlerFunc {
```suggestion
func (s *UpdateHandler) Update(w http.ResponseWriter, r *http.Request) {
```

2024-10-14 11:30 UTC, arttet commented on service/service.go
> +type ServiceRepository interface {
[CLARIFICATION] Why is it here?

2024-10-14 13:49 UTC, sur1k1 commented on service/service.go
> +type ServiceRepository interface {
https://medium.com/@deanrubin/the-three-layered-architecture-fe30cb0e4a6#:~:text=The%20presentation%20layer%20is%20the,Update%20or%20Delete)%20operation%20flow

2024-10-14 13:53 UTC, sur1k1 commented on service/service.go
> +type ServiceRepository interface {
https://github.com/bxcodec/go-clean-arch/blob/master/internal/rest/article.go

2024-10-15 16:54 UTC, merged